openapi: 3.0.0
info:
    title: Log Entry API
    description: Log Entry API
    version: 0.1

servers:
    - url: http://127.0.0.1:8880/

paths:
    /logs:
        get:
            summary: Returns a list of logs
            responses:
                '200':
                    description: JSON array of logs
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
